FROM websphere-liberty:webProfile7
MAINTAINER IBM Java engineering at IBM Cloud

RUN mkdir -m 777 -p /config/resources

# COPY src/main/resources/.m2 /root/.m2


# Upgrade to production license if URL to JAR provided
ARG LICENSE_JAR_URL
RUN \
  if [ $LICENSE_JAR_URL ]; then \
    wget $LICENSE_JAR_URL -O /tmp/license.jar \
    && java -jar /tmp/license.jar -acceptLicense /opt/ibm \
    && rm /tmp/license.jar; \
  fi
